[package]
authors = ["Justin Hurst <jryanhurst@gmail.com"]
name = "rustlike"
version = "0.1.0"

[dependencies]
sdl2 = "0.30.0"

[features]
default = []
use_sdl2_mac_framework = ["sdl2/use_mac_framework"]

[dev-dependencies]
rspec = "1.0.0-beta.4"
expect = "0.0.1"
