(function() {var implementors = {};
implementors["quote"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"quote/struct.Tokens.html\" title=\"struct quote::Tokens\">Tokens</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"quote/struct.Ident.html\" title=\"struct quote::Ident\">Ident</a>",];
implementors["sdl2"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"sdl2_sys/struct.SDL_Rect.html\" title=\"struct sdl2_sys::SDL_Rect\">SDL_Rect</a>&gt; for <a class=\"struct\" href=\"sdl2/rect/struct.Rect.html\" title=\"struct sdl2::rect::Rect\">Rect</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"sdl2_sys/struct.SDL_Point.html\" title=\"struct sdl2_sys::SDL_Point\">SDL_Point</a>&gt; for <a class=\"struct\" href=\"sdl2/rect/struct.Point.html\" title=\"struct sdl2::rect::Point\">Point</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"sdl2/surface/struct.SurfaceRef.html\" title=\"struct sdl2::surface::SurfaceRef\">SurfaceRef</a>&gt; for <a class=\"struct\" href=\"sdl2/surface/struct.SurfaceRef.html\" title=\"struct sdl2::surface::SurfaceRef\">SurfaceRef</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"sdl2/surface/struct.SurfaceRef.html\" title=\"struct sdl2::surface::SurfaceRef\">SurfaceRef</a>&gt; for <a class=\"struct\" href=\"sdl2/surface/struct.Surface.html\" title=\"struct sdl2::surface::Surface\">Surface</a>&lt;'a&gt;",];
implementors["syn"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"syn/struct.Ident.html\" title=\"struct syn::Ident\">Ident</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
