(function() {var implementors = {};
implementors["rl_gl"] = ["impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"rl_gl/attributes/struct.AttributeValue.html\" title=\"struct rl_gl::attributes::AttributeValue\">AttributeValue</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"enum\" href=\"rl_gl/attributes/enum.AttributeKind.html\" title=\"enum rl_gl::attributes::AttributeKind\">AttributeKind</a>&gt; + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.PartialEq.html\" title=\"trait core::cmp::PartialEq\">PartialEq</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>,&nbsp;</span>",];
implementors["sdl2"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"sdl2/rect/struct.Rect.html\" title=\"struct sdl2::rect::Rect\">Rect</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"sdl2/rect/struct.Point.html\" title=\"struct sdl2::rect::Point\">Point</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"sdl2/surface/struct.Surface.html\" title=\"struct sdl2::surface::Surface\">Surface</a>&lt;'a&gt;","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"sdl2/video/struct.WindowSurfaceRef.html\" title=\"struct sdl2::video::WindowSurfaceRef\">WindowSurfaceRef</a>&lt;'a&gt;","impl&lt;T:&nbsp;<a class=\"trait\" href=\"sdl2/render/trait.RenderTarget.html\" title=\"trait sdl2::render::RenderTarget\">RenderTarget</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"sdl2/render/struct.Canvas.html\" title=\"struct sdl2::render::Canvas\">Canvas</a>&lt;T&gt;","impl&lt;'a, CB:&nbsp;<a class=\"trait\" href=\"sdl2/audio/trait.AudioCallback.html\" title=\"trait sdl2::audio::AudioCallback\">AudioCallback</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"sdl2/audio/struct.AudioDeviceLockGuard.html\" title=\"struct sdl2::audio::AudioDeviceLockGuard\">AudioDeviceLockGuard</a>&lt;'a, CB&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
